spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

jwt.expiration: 9000
jwt.secret: MinhaChavaSuperHiperMegaSecreta2026
ai.apikey: ${AI_API_KEY}
ai.apimodel: ${AI_API_MODEL}